# This is a basic workflow to help you get started with Actions

name: Publish To pub.dev

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Dart/Flutter package
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          # Google Account credential
          credential: ${{ secrets.GOOGLE_PASSWORD }}
          flutter_package: true
          skip_test: true
          package_directory: "."
          dry_run: false
